name: Makefile CI

on:
  push:
    branches: [ "mpx" ]
  pull_request:
    branches: [ "mpx" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: sudo apt update && sudo apt install -y clang make nasm binutils-i686-linux-gnu

    - name: Build
      run: make
